name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pg-core:
    name: Build & Test
    strategy:
      matrix:
        os: [windows-latest]
        configuration: [Debug, Release]
    runs-on: ${{ matrix.os }}
    env:
      project_path: PG.Core/PG.Core/PG.Core.csproj
      test_project_path: PG.Core/PG.Core.Test/PG.Core.Test.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Build 
      run: dotnet build $env:project_path
    - name: Unit Tests
      run: dotnet test $env:test_project_path
      env:
        Configuration: ${{ matrix.configuration }}
