name: Petroglyph Tools .NET Core Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_project: [PG.Core/PG.Core.Test/PG.Core.Test.csproj, PG.Commons/PG.Commons.Test/PG.Commons.Test.csproj, PG.StarWarsGame/PG.StarWarsGame.Test/PG.StarWarsGame.Test.csproj, PG.StarWarsGame.Files.DAT/PG.StarWarsGame.Files.DAT.Test/PG.StarWarsGame.Files.DAT.Test.csproj, PG.StarWarsGame.Files.MEG/PG.StarWarsGame.Files.MEG.Test/PG.StarWarsGame.Files.MEG.Test.csproj, PG.StarWarsGame.Files.MTD/PG.StarWarsGame.Files.MTD.Test/PG.StarWarsGame.Files.MTD.Test.csproj, PG.StarWarsGame.Localisation/PG.StarWarsGame.Localisation.Test/PG.StarWarsGame.Localisation.Test.csproj]
      fail-fast: false
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Generate Code Coverage Report
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish Coverage Report
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.COVERALL_TOKEN }}
        path-to-lcov: ./TestResults/coverage.info
