name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        net: [3.1.200, 2.1.804]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.net }}
    - name: Build with dotnet
      run: dotnet build
