name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pg-core:
    name: Build & Test
    strategy:
      matrix:
        os: [windows-latest]
        project: [PG.Core/PG.Core/PG.Core.csproj, PG.Commons/PG.Commons/PG.Commons.csproj]
        test_project: [PG.Core/PG.Core.Test/PG.Core.Test.csproj, PG.Commons/PG.Commons.Test/PG.Commons.Test.csproj]
        configuration: [Debug, Release]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Build 
      run: dotnet build ${{ matrix.project }}
    - name: Unit Tests
      run: dotnet test ${{ matrix.test_project }}
      env:
        Configuration: ${{ matrix.configuration }}
