name: Petroglyph Tools .NET Core Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest, macos-latest]
        configuration: [Debug, Release]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: |
        dotnet build PG.Core/PG.Core/PG.Core.csproj
        dotnet build PG.Commons/PG.Commons/PG.Commons.csproj
        dotnet build PG.StarWarsGame/PG.StarWarsGame/PG.StarWarsGame.csproj
        dotnet build PG.StarWarsGame.Files.DAT/PG.StarWarsGame.Files.DAT/PG.StarWarsGame.Files.DAT.csproj
        dotnet build PG.StarWarsGame.Files.MEG/PG.StarWarsGame.Files.MEG/PG.StarWarsGame.Files.MEG.csproj
        dotnet build PG.StarWarsGame.Files.MTD/PG.StarWarsGame.Files.MTD/PG.StarWarsGame.Files.MTD.csproj
        dotnet build PG.StarWarsGame.Localisation/PG.StarWarsGame.Localisation/PG.StarWarsGame.Localisation.csproj
    - name: Unit Test
      run: |
        dotnet test PG.Core/PG.Core.Test/PG.Core.Test.csproj
        dotnet test PG.Commons/PG.Commons.Test/PG.Commons.Test.csproj
        dotnet test PG.StarWarsGame/PG.StarWarsGame.Test/PG.StarWarsGame.Test.csproj
        dotnet test PG.StarWarsGame.Files.DAT/PG.StarWarsGame.Files.DAT.Test/PG.StarWarsGame.Files.DAT.Test.csproj
        dotnet test PG.StarWarsGame.Files.MEG/PG.StarWarsGame.Files.MEG.Test/PG.StarWarsGame.Files.MEG.Test.csproj
        dotnet test PG.StarWarsGame.Files.MTD/PG.StarWarsGame.Files.MTD.Test/PG.StarWarsGame.Files.MTD.Test.csproj
        dotnet test PG.StarWarsGame.Localisation/PG.StarWarsGame.Localisation.Test/PG.StarWarsGame.Localisation.Test.csproj
      env:
        Configuration: ${{ matrix.configuration }}
