name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest]
        configuration: [Debug, Release]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: |
        dotnet build PG.Core/PG.Core/PG.Core.csproj
        dotnet build PG.Commons/PG.Commons/PG.Commons.csproj
    - name: Unit Test
      run: |
        dotnet test PG.Core/PG.Core.Test/PG.Core.Test.csproj
        dotnet test PG.Commons/PG.Commons.Test/PG.Commons.Test.csproj
      env:
        Configuration: ${{ matrix.configuration }}
