name: Petroglyph Tools .NET Core Build & Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    name: Build & Test
    strategy:
      matrix:
        # os: [windows-latest,ubuntu-latest, macos-latest]
        os: [windows-latest, ubuntu-latest]
        # configuration: [Debug, Release]
        configuration: [Release]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Build
        run: |
          dotnet build PG.Commons/PG.Commons/PG.Commons.csproj
          dotnet build PG.StarWarsGame.Files.DAT/PG.StarWarsGame.Files.DAT/PG.StarWarsGame.Files.DAT.csproj
          dotnet build PG.StarWarsGame.Files.MEG/PG.StarWarsGame.Files.MEG/PG.StarWarsGame.Files.MEG.csproj
          dotnet build PG.StarWarsGame.Components.Localisation/PG.StarWarsGame.Components.Localisation/PG.StarWarsGame.Components.Localisation.csproj
      - name: Unit Test
        run: |
          dotnet test PG.Commons/PG.Commons.Test/PG.Commons.Test.csproj
          dotnet test PG.StarWarsGame.Files.DAT/PG.StarWarsGame.Files.DAT.Test/PG.StarWarsGame.Files.DAT.Test.csproj
          dotnet test PG.StarWarsGame.Files.MEG/PG.StarWarsGame.Files.MEG.Test/PG.StarWarsGame.Files.MEG.Test.csproj
          dotnet test PG.StarWarsGame.Components.Localisation/PG.StarWarsGame.Components.Localisation/PG.StarWarsGame.Components.Localisation.csproj
        env:
          Configuration: ${{ matrix.configuration }}
